name: identity

on: push

jobs:
  Create:
    runs-on: ubuntu-latest
    steps:
      - name: creating
        run: echo Helloworld >new.txt
  Read:
    runs-on: ubuntu-latest
    steps:
      - name: reading
        run: cat new.txt