name: identity

on: push

jobs:
  Create:
    runs-on: ubuntu-latest
    steps:
      - name: creating
        run: echo Helloworld > new.txt

      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: myfile
          path: new.txt

  Read:
    needs: Create
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: actions/download-artifact@v4
        with:
          name: myfile

      - name: reading
        run: cat new.txt
