name: node-ci

on: push

jobs:
  Install:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Restore cache
        uses: actions/cache@v4
        wtih:
          path: ~/ .npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json')}}
 
      - name: install
        run: npm install
  Run:
    needs: Install
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Restore cache
        uses: actions/cache@v4
        wtih:
          path: ~/ .npm
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json')}}
          
      - name: running
        run: npm run build