name: Dockerhub Registry

on:
  workflow_dispatch:

jobs:
  Build_Push :
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login
        run: |
          echo " Logging ${{ secrets.Dockerhub_password }} | \
          docker login -u ${ secrets.Dockerhub_username }} --password-stdin
      - name: Build
        run: docker build -t ${{ Dockerhub_username }}/demo:latest .

      - name: Push image
        run: |
          docker push ${{ Dockerhub_username }}/demo:latest
